# Generated by Django 3.1.7 on 2023-06-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MemoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('parent_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_manager.memo')),
            ],
        ),
    ]
