# Generated by Django 3.1.7 on 2023-06-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0001_create_memo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoitem',
            name='parent_memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_items', to='memo_manager.memo'),
        ),
    ]
