# Generated by Django 3.1.7 on 2023-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0002_add_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoitem',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
