# Generated by Django 3.1.7 on 2023-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0003_add_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoitem',
            name='order',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
