# Generated by Django 3.1.7 on 2023-06-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0004_change_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='reminder_at',
            field=models.DateField(),
        ),
    ]
