# Generated by Django 3.1.7 on 2023-06-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0005_update_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='reminder_at',
        ),
    ]
