# Generated by Django 3.1.7 on 2023-06-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_manager', '0006_redesign_memo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoitem',
            old_name='is_complete',
            new_name='is_completed',
        ),
    ]
